# TRTR Dataset E

In [2]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [3]:
#define directory of functions and actual directory
HOME_PATH = '' #home path of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [4]:
#read real dataset
train_data = pd.read_csv(HOME_PATH + 'REAL DATASETS/TRAIN DATASETS/E_PimaIndiansDiabetes_Real_Train.csv')
categorical_columns = ['Outcome']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,84,0,0,0,0.0,0.304,21,0
1,9,112,82,24,0,28.2,1.282,50,1
2,1,139,46,19,83,28.7,0.654,22,0
3,0,161,50,0,0,21.9,0.254,65,0
4,6,134,80,37,370,46.2,0.238,46,1
...,...,...,...,...,...,...,...,...,...
609,5,139,64,35,140,28.6,0.411,26,0
610,1,96,122,0,0,22.4,0.207,27,0
611,10,101,86,37,0,45.6,1.136,38,1
612,0,141,0,0,0,42.4,0.205,29,1
613,0,125,96,0,0,22.5,0.262,21,0

In [5]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'REAL DATASETS/TEST DATASETS/E_PimaIndiansDiabetes_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98,58,33,190,34.0,0.430,43,0
1,2,112,75,32,0,35.7,0.148,21,0
2,2,108,64,0,0,30.8,0.158,21,0
3,8,107,80,0,0,24.6,0.856,34,0
4,7,136,90,0,0,29.9,0.210,50,0
...,...,...,...,...,...,...,...,...,...
149,9,165,88,0,0,30.4,0.302,49,1
150,1,77,56,30,56,33.3,1.251,24,0
151,8,95,72,0,0,36.8,0.485,57,0
152,2,146,70,38,360,28.0,0.337,29,1
153,8,74,70,40,49,35.3,0.705,39,0

In [6]:
target = 'Outcome'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(614, 9)
Outcome
0    401
1    213
dtype: int64
#####################################
Test data
(154, 9)
Outcome
0    99
1    55
dtype: int64

## 2. Pre-process training data

In [7]:
target = 'Outcome'
categorical_columns = None
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = None

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((614, 8), (614,))

## 3. Preprocess test data

In [8]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((154, 8), (154,))

## 4. Create a dataset to save the results

In [9]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [10]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = results.append(rf_results, ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.1s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.2s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.7338     0.7349  0.7338  0.7343

## 5. Train and Evaluate KNeighbors Classifier

In [11]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = results.append(knn_results, ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.6883     0.6782  0.6883  0.6802

## 6. Train and evaluate Decision Tree Classifier

In [12]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = results.append(dt_results, ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.7792     0.7835  0.7792  0.7808

## 7. Train and evaluate Support Vector Machines Classifier

In [13]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = results.append(svm_results, ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall    f1
0   SVM     0.461     0.5452   0.461  0.46

## 8. Train and evaluate Multilayer Perceptron Classifier

In [14]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = results.append(mlp_results, ignore_index=True)
mlp_results

Iteration 1, loss = 0.67894164
Iteration 2, loss = 0.63957689
Iteration 3, loss = 0.61049009
Iteration 4, loss = 0.58593050
Iteration 5, loss = 0.56227293
Iteration 6, loss = 0.53861149
Iteration 7, loss = 0.51577049
Iteration 8, loss = 0.49566069
Iteration 9, loss = 0.47839355
Iteration 10, loss = 0.46719567
Iteration 11, loss = 0.45778521
Iteration 12, loss = 0.45115816
Iteration 13, loss = 0.44815100
Iteration 14, loss = 0.44945862
Iteration 15, loss = 0.44392758
Iteration 16, loss = 0.43576709
Iteration 17, loss = 0.43164609
Iteration 18, loss = 0.42800737
Iteration 19, loss = 0.42477162
Iteration 20, loss = 0.42101884
Iteration 21, loss = 0.41910086
Iteration 22, loss = 0.41647330
Iteration 23, loss = 0.41436486
Iteration 24, loss = 0.41134364
Iteration 25, loss = 0.40767881
Iteration 26, loss = 0.40581910
Iteration 27, loss = 0.40550827
Iteration 28, loss = 0.40384279
Iteration 29, loss = 0.40008713
Iteration 30, loss = 0.39903273
Iteration 31, loss = 0.40192260
Iteration 32, loss = 0.39762114
Iteration 33, loss = 0.39405628
Iteration 34, loss = 0.39228451
Iteration 35, loss = 0.38940596
Iteration 36, loss = 0.38922092
Iteration 37, loss = 0.38674806
Iteration 38, loss = 0.38458387
Iteration 39, loss = 0.38463121
Iteration 40, loss = 0.38574401
Iteration 41, loss = 0.38741682
Iteration 42, loss = 0.38627263
Iteration 43, loss = 0.38310655
Iteration 44, loss = 0.38135730
Iteration 45, loss = 0.37448830
Iteration 46, loss = 0.37050126
Iteration 47, loss = 0.37169793
Iteration 48, loss = 0.37133681
Iteration 49, loss = 0.36662132
Iteration 50, loss = 0.37355523
Iteration 51, loss = 0.37516486
Iteration 52, loss = 0.36719970
Iteration 53, loss = 0.36632889
Iteration 54, loss = 0.36802616
Iteration 55, loss = 0.36150981
Iteration 56, loss = 0.36521973
Iteration 57, loss = 0.36074197
Iteration 58, loss = 0.35694633
Iteration 59, loss = 0.35920199
Iteration 60, loss = 0.35586294
Iteration 61, loss = 0.35861107
Iteration 62, loss = 0.35368061
Iteration 63, loss = 0.35179461
Iteration 64, loss = 0.36664190
Iteration 65, loss = 0.35274352
Iteration 66, loss = 0.34818952
Iteration 67, loss = 0.34867817
Iteration 68, loss = 0.34249452
Iteration 69, loss = 0.34534374
Iteration 70, loss = 0.34228059
Iteration 71, loss = 0.34126142
Iteration 72, loss = 0.34937499
Iteration 73, loss = 0.34509654
Iteration 74, loss = 0.33899247
Iteration 75, loss = 0.33511413
Iteration 76, loss = 0.33470593
Iteration 77, loss = 0.33441928
Iteration 78, loss = 0.33174842
Iteration 79, loss = 0.32935675
Iteration 80, loss = 0.32807916
Iteration 81, loss = 0.32573592
Iteration 82, loss = 0.32533292
Iteration 83, loss = 0.32257240
Iteration 84, loss = 0.32065980
Iteration 85, loss = 0.31995823
Iteration 86, loss = 0.32104016
Iteration 87, loss = 0.31577562
Iteration 88, loss = 0.31623156
Iteration 89, loss = 0.31579841
Iteration 90, loss = 0.31171968
Iteration 91, loss = 0.31224141
Iteration 92, loss = 0.30625880
Iteration 93, loss = 0.30761075
Iteration 94, loss = 0.30281940
Iteration 95, loss = 0.29885539
Iteration 96, loss = 0.29943457
Iteration 97, loss = 0.29608634
Iteration 98, loss = 0.29597443
Iteration 99, loss = 0.29854878
Iteration 100, loss = 0.29896493
Iteration 101, loss = 0.29484870
Iteration 102, loss = 0.30052014
Iteration 103, loss = 0.29289932
Iteration 104, loss = 0.28532444
Iteration 105, loss = 0.28813958
Iteration 106, loss = 0.29182753
Iteration 107, loss = 0.28798193
Iteration 108, loss = 0.28309736
Iteration 109, loss = 0.28134946
Iteration 110, loss = 0.27897914
Iteration 111, loss = 0.27658773
Iteration 112, loss = 0.27306440
Iteration 113, loss = 0.27315076
Iteration 114, loss = 0.27386945
Iteration 115, loss = 0.27476492
Iteration 116, loss = 0.26991798
Iteration 117, loss = 0.26876862
Iteration 118, loss = 0.27087423
Iteration 119, loss = 0.26599927
Iteration 120, loss = 0.26736588
Iteration 121, loss = 0.26324544
Iteration 122, loss = 0.26196832
Iteration 123, loss = 0.25717801
Iteration 124, loss = 0.25582448
Iteration 125, loss = 0.25276161
Iteration 126, loss = 0.25301841
Iteration 127, loss = 0.25177125
Iteration 128, loss = 0.24994039
Iteration 129, loss = 0.24766257
Iteration 130, loss = 0.24561592
Iteration 131, loss = 0.24139682
Iteration 132, loss = 0.23976929
Iteration 133, loss = 0.23824900
Iteration 134, loss = 0.23465430
Iteration 135, loss = 0.23380704
Iteration 136, loss = 0.23308514
Iteration 137, loss = 0.22899478
Iteration 138, loss = 0.22787791
Iteration 139, loss = 0.22449394
Iteration 140, loss = 0.22478406
Iteration 141, loss = 0.22130761
Iteration 142, loss = 0.21965424
Iteration 143, loss = 0.21799887
Iteration 144, loss = 0.21394807
Iteration 145, loss = 0.21258675
Iteration 146, loss = 0.21191084
Iteration 147, loss = 0.20707790
Iteration 148, loss = 0.20468855
Iteration 149, loss = 0.20414025
Iteration 150, loss = 0.20101882
Iteration 151, loss = 0.19720108
Iteration 152, loss = 0.19805501
Iteration 153, loss = 0.20513289
Iteration 154, loss = 0.19811662
Iteration 155, loss = 0.19399978
Iteration 156, loss = 0.19801495
Iteration 157, loss = 0.18431518
Iteration 158, loss = 0.19050204
Iteration 159, loss = 0.18467437
Iteration 160, loss = 0.18729859
Iteration 161, loss = 0.17928114
Iteration 162, loss = 0.18952027
Iteration 163, loss = 0.18870955
Iteration 164, loss = 0.20178604
Iteration 165, loss = 0.17818695
Iteration 166, loss = 0.18334340
Iteration 167, loss = 0.18659690
Iteration 168, loss = 0.18089155
Iteration 169, loss = 0.17477241
Iteration 170, loss = 0.16715295
Iteration 171, loss = 0.17882667
Iteration 172, loss = 0.16660833
Iteration 173, loss = 0.19813899
Iteration 174, loss = 0.16331083
Iteration 175, loss = 0.16708331
Iteration 176, loss = 0.15425892
Iteration 177, loss = 0.15586030
Iteration 178, loss = 0.15010802
Iteration 179, loss = 0.14658477
Iteration 180, loss = 0.14880915
Iteration 181, loss = 0.15073513
Iteration 182, loss = 0.14714756
Iteration 183, loss = 0.14533205
Iteration 184, loss = 0.14020373
Iteration 185, loss = 0.13524785
Iteration 186, loss = 0.13776294
Iteration 187, loss = 0.13683171
Iteration 188, loss = 0.13126720
Iteration 189, loss = 0.14407456
Iteration 190, loss = 0.13068613
Iteration 191, loss = 0.12343386
Iteration 192, loss = 0.13060613
Iteration 193, loss = 0.12237753
Iteration 194, loss = 0.12493796
Iteration 195, loss = 0.12442657
Iteration 196, loss = 0.11929666
Iteration 197, loss = 0.11815454
Iteration 198, loss = 0.12210409
Iteration 199, loss = 0.12103340
Iteration 200, loss = 0.11336139
Iteration 201, loss = 0.11297467
Iteration 202, loss = 0.11693737
Iteration 203, loss = 0.12484229
Iteration 204, loss = 0.11233498
Iteration 205, loss = 0.13403155
Iteration 206, loss = 0.11891232
Iteration 207, loss = 0.14345261
Iteration 208, loss = 0.12072638
Iteration 209, loss = 0.11867212
Iteration 210, loss = 0.10763909
Iteration 211, loss = 0.11110870
Iteration 212, loss = 0.10337855
Iteration 213, loss = 0.09845228
Iteration 214, loss = 0.09788252
Iteration 215, loss = 0.10314967
Iteration 216, loss = 0.09330299
Iteration 217, loss = 0.11748715
Iteration 218, loss = 0.10206762
Iteration 219, loss = 0.09774020
Iteration 220, loss = 0.09343900
Iteration 221, loss = 0.10016139
Iteration 222, loss = 0.10649110
Iteration 223, loss = 0.12422004
Iteration 224, loss = 0.10553422
Iteration 225, loss = 0.09257298
Iteration 226, loss = 0.10757059
Iteration 227, loss = 0.09203155
Iteration 228, loss = 0.09588430
Iteration 229, loss = 0.10308775
Iteration 230, loss = 0.10066270
Iteration 231, loss = 0.09447677
Iteration 232, loss = 0.08020789
Iteration 233, loss = 0.08251899
Iteration 234, loss = 0.08728404
Iteration 235, loss = 0.07857184
Iteration 236, loss = 0.08189668
Iteration 237, loss = 0.08879746
Iteration 238, loss = 0.08161607
Iteration 239, loss = 0.07801894
Iteration 240, loss = 0.07607035
Iteration 241, loss = 0.07743978
Iteration 242, loss = 0.07116578
Iteration 243, loss = 0.06562196
Iteration 244, loss = 0.06490390
Iteration 245, loss = 0.06317523
Iteration 246, loss = 0.06372418
Iteration 247, loss = 0.06092728
Iteration 248, loss = 0.06226465
Iteration 249, loss = 0.06474004
Iteration 250, loss = 0.05935483
Iteration 251, loss = 0.06336300
Iteration 252, loss = 0.05617547
Iteration 253, loss = 0.06018533
Iteration 254, loss = 0.05549545
Iteration 255, loss = 0.05888306
Iteration 256, loss = 0.05434584
Iteration 257, loss = 0.05196640
Iteration 258, loss = 0.05084858
Iteration 259, loss = 0.04927966
Iteration 260, loss = 0.04853853
Iteration 261, loss = 0.04728442
Iteration 262, loss = 0.04717996
Iteration 263, loss = 0.04757437
Iteration 264, loss = 0.04676327
Iteration 265, loss = 0.04574084
Iteration 266, loss = 0.04529613
Iteration 267, loss = 0.04463157
Iteration 268, loss = 0.04547875
Iteration 269, loss = 0.04493089
Iteration 270, loss = 0.04341055
Iteration 271, loss = 0.04164393
Iteration 272, loss = 0.04225849
Iteration 273, loss = 0.04782124
Iteration 274, loss = 0.04570673
Iteration 275, loss = 0.04183219
Iteration 276, loss = 0.04408740
Iteration 277, loss = 0.03940849
Iteration 278, loss = 0.03795412
Iteration 279, loss = 0.03822971
Iteration 280, loss = 0.03812701
Iteration 281, loss = 0.04205302
Iteration 282, loss = 0.04049212
Iteration 283, loss = 0.03627526
Iteration 284, loss = 0.03601935
Iteration 285, loss = 0.03639506
Iteration 286, loss = 0.03687247
Iteration 287, loss = 0.03585105
Iteration 288, loss = 0.03702062
Iteration 289, loss = 0.03341198
Iteration 290, loss = 0.03369484
Iteration 291, loss = 0.03752534
Iteration 292, loss = 0.03345556
Iteration 293, loss = 0.03147714
Iteration 294, loss = 0.02967297
Iteration 295, loss = 0.03274404
Iteration 296, loss = 0.03014983
Iteration 297, loss = 0.02971939
Iteration 298, loss = 0.03007812
Iteration 299, loss = 0.02882704
Iteration 300, loss = 0.03062535

  model  accuracy  precision  recall      f1
0   MLP    0.6753     0.6753  0.6753  0.6753

## 9. Save results file

In [15]:
results.to_csv('RESULTS/models_results_real.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.7338     0.7349  0.7338  0.7343
1   KNN    0.6883     0.6782  0.6883  0.6802
2    DT    0.7792     0.7835  0.7792  0.7808
3   SVM    0.4610     0.5452  0.4610  0.4600
4   MLP    0.6753     0.6753  0.6753  0.6753