# TSTR WGANGP Dataset E

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
from sklearn.preprocessing import LabelEncoder
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
HOME_PATH = '' #home path of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(HOME_PATH + 'SYNTHETIC DATASETS/WGANGP/E_PimaIndiansDiabetes_Synthetic_WGANGP.csv')
categorical_columns = ['Outcome']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,128,77,7,25,27.523672,0.330995,37,0
1,2,127,76,10,43,26.481262,0.347808,33,0
2,2,128,79,7,34,26.954290,0.311545,38,0
3,2,130,78,8,34,25.400051,0.339302,35,0
4,1,115,78,11,48,27.617651,0.316792,32,0
...,...,...,...,...,...,...,...,...,...
609,2,117,71,14,60,28.184755,0.345568,30,0
610,2,123,75,7,30,29.951437,0.359797,35,0
611,2,126,74,11,53,27.091782,0.317798,33,0
612,2,129,74,9,47,26.547909,0.326646,33,0
613,2,136,25,7,21,27.907232,0.293885,30,1

In [4]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'REAL DATASETS/TEST DATASETS/E_PimaIndiansDiabetes_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,98,58,33,190,34.0,0.430,43,0
1,2,112,75,32,0,35.7,0.148,21,0
2,2,108,64,0,0,30.8,0.158,21,0
3,8,107,80,0,0,24.6,0.856,34,0
4,7,136,90,0,0,29.9,0.210,50,0
...,...,...,...,...,...,...,...,...,...
149,9,165,88,0,0,30.4,0.302,49,1
150,1,77,56,30,56,33.3,1.251,24,0
151,8,95,72,0,0,36.8,0.485,57,0
152,2,146,70,38,360,28.0,0.337,29,1
153,8,74,70,40,49,35.3,0.705,39,0

In [5]:
target = 'Outcome'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(614, 9)
Outcome
0    561
1     53
dtype: int64
#####################################
Test data
(154, 9)
Outcome
0    99
1    55
dtype: int64

## 2. Pre-process training data

In [6]:
target = 'Outcome'
categorical_columns = None
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = None

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((614, 8), (614,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((154, 8), (154,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = results.append(rf_results, ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.1s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.2s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF     0.513     0.5596   0.513  0.5229

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = results.append(knn_results, ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.6234      0.587  0.6234  0.5869

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = results.append(dt_results, ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.5325     0.5544  0.5325  0.5404

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
svm_results['model'] = svm_results['model'].replace(['MLP'],'SVM')
results = results.append(svm_results, ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall      f1
0   SVM     0.513     0.5372   0.513  0.5216

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = results.append(mlp_results, ignore_index=True)
mlp_results

Iteration 1, loss = 0.66473094
Iteration 2, loss = 0.56789142
Iteration 3, loss = 0.49183180
Iteration 4, loss = 0.42440190
Iteration 5, loss = 0.36167319
Iteration 6, loss = 0.30579419
Iteration 7, loss = 0.26148774
Iteration 8, loss = 0.22500130
Iteration 9, loss = 0.19423659
Iteration 10, loss = 0.16695750
Iteration 11, loss = 0.14742637
Iteration 12, loss = 0.13267459
Iteration 13, loss = 0.11869229
Iteration 14, loss = 0.10780215
Iteration 15, loss = 0.10161612
Iteration 16, loss = 0.09566945
Iteration 17, loss = 0.08792518
Iteration 18, loss = 0.08448760
Iteration 19, loss = 0.08140567
Iteration 20, loss = 0.07815226
Iteration 21, loss = 0.07339248
Iteration 22, loss = 0.06886550
Iteration 23, loss = 0.06812127
Iteration 24, loss = 0.06515121
Iteration 25, loss = 0.07015340
Iteration 26, loss = 0.06594476
Iteration 27, loss = 0.05899275
Iteration 28, loss = 0.06417627
Iteration 29, loss = 0.06193635
Iteration 30, loss = 0.05575258
Iteration 31, loss = 0.05453808
Iteration 32, loss = 0.05517998
Iteration 33, loss = 0.05269342
Iteration 34, loss = 0.04783618
Iteration 35, loss = 0.04592793
Iteration 36, loss = 0.04765253
Iteration 37, loss = 0.04820798
Iteration 38, loss = 0.04411240
Iteration 39, loss = 0.04116725
Iteration 40, loss = 0.04076931
Iteration 41, loss = 0.03980006
Iteration 42, loss = 0.03869747
Iteration 43, loss = 0.03830464
Iteration 44, loss = 0.03707052
Iteration 45, loss = 0.03549119
Iteration 46, loss = 0.03677693
Iteration 47, loss = 0.03500294
Iteration 48, loss = 0.03434011
Iteration 49, loss = 0.03397111
Iteration 50, loss = 0.03184863
Iteration 51, loss = 0.03365504
Iteration 52, loss = 0.03191293
Iteration 53, loss = 0.03091295
Iteration 54, loss = 0.03008832
Iteration 55, loss = 0.02941032
Iteration 56, loss = 0.03052711
Iteration 57, loss = 0.03288637
Iteration 58, loss = 0.02905961
Iteration 59, loss = 0.02918465
Iteration 60, loss = 0.02970133
Iteration 61, loss = 0.02737193
Iteration 62, loss = 0.02642199
Iteration 63, loss = 0.02630673
Iteration 64, loss = 0.02712369
Iteration 65, loss = 0.02441695
Iteration 66, loss = 0.02568691
Iteration 67, loss = 0.02685520
Iteration 68, loss = 0.02530516
Iteration 69, loss = 0.02518877
Iteration 70, loss = 0.02815823
Iteration 71, loss = 0.02497001
Iteration 72, loss = 0.02318028
Iteration 73, loss = 0.02403172
Iteration 74, loss = 0.02270740
Iteration 75, loss = 0.02190265
Iteration 76, loss = 0.02138096
Iteration 77, loss = 0.02067969
Iteration 78, loss = 0.02026505
Iteration 79, loss = 0.01939495
Iteration 80, loss = 0.01882227
Iteration 81, loss = 0.01994817
Iteration 82, loss = 0.01976782
Iteration 83, loss = 0.01970066
Iteration 84, loss = 0.02069992
Iteration 85, loss = 0.02183188
Iteration 86, loss = 0.01991406
Iteration 87, loss = 0.02239758
Iteration 88, loss = 0.02216003
Iteration 89, loss = 0.02074442
Iteration 90, loss = 0.03264418
Iteration 91, loss = 0.02535374
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.6299     0.5829  0.6299  0.5713

## 9. Save results file

In [14]:
results.to_csv('RESULTS/models_results_wgangp.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.5130     0.5596  0.5130  0.5229
1   KNN    0.6234     0.5870  0.6234  0.5869
2    DT    0.5325     0.5544  0.5325  0.5404
3   SVM    0.5130     0.5372  0.5130  0.5216
4   MLP    0.6299     0.5829  0.6299  0.5713