# TSTR GM Dataset C - Obesity

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
HOME_PATH = '' #home path of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(HOME_PATH + 'SYNTHETIC DATASETS/GM/C_Obesity_Data_Synthetic_GM.csv')
categorical_columns = ['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE','SCC','CALC','MTRANS','Obesity_level']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_level
0,Female,21,1.736983,96.575084,yes,yes,3.043926,3.229494,Sometimes,no,2.767918,no,0.559224,0.723408,Sometimes,Public_Transportation,Insufficient_Weight
1,Male,27,1.791849,132.568140,yes,yes,2.743510,3.213367,Sometimes,no,2.543950,no,-0.718087,0.050567,Sometimes,Public_Transportation,Obesity_Type_II
2,Male,16,1.849836,80.521419,no,yes,2.474037,2.287594,Frequently,no,3.005978,no,0.120772,1.338905,Sometimes,Public_Transportation,Overweight_Level_I
3,Male,20,1.753469,107.888290,yes,yes,2.575027,2.686841,Sometimes,no,2.198808,no,1.113582,0.739439,Sometimes,Public_Transportation,Overweight_Level_II
4,Female,33,1.616082,112.720873,yes,yes,2.779278,1.335992,Sometimes,no,2.765885,no,1.447929,1.321864,Sometimes,Public_Transportation,Obesity_Type_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Male,23,1.729979,107.686391,yes,yes,3.038139,3.429195,Sometimes,no,1.447293,no,0.157166,0.764616,Sometimes,Automobile,Obesity_Type_III
1684,Male,24,1.722470,122.682563,yes,yes,2.556549,3.763153,Sometimes,no,2.444046,no,2.250645,0.188289,Sometimes,Public_Transportation,Obesity_Type_III
1685,Female,26,1.761826,88.618928,yes,yes,2.240721,3.604517,Sometimes,no,2.886618,no,0.781996,0.615303,Sometimes,Automobile,Obesity_Type_I
1686,Female,21,1.508331,102.850821,yes,yes,2.048591,1.967142,Sometimes,no,2.308040,no,-0.629877,-0.509730,Sometimes,Public_Transportation,Obesity_Type_I
1687,Female,25,1.587326,131.071269,yes,yes,2.548532,1.763349,Sometimes,no,1.135346,no,1.327956,1.790538,no,Public_Transportation,Obesity_Type_III

In [4]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'REAL DATASETS/TEST DATASETS/C_Obesity_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_level
0,Female,20,1.76,53.70,yes,yes,2.000000,3.891994,Frequently,no,1.863930,no,2.870127,2.000000,no,Public_Transportation,Insufficient_Weight
1,Female,26,1.62,111.00,yes,yes,3.000000,3.000000,Sometimes,no,2.704315,no,0.000000,0.322666,Sometimes,Public_Transportation,Obesity_Type_III
2,Male,18,1.85,60.00,yes,yes,3.000000,4.000000,Sometimes,no,2.000000,yes,2.000000,0.000000,Sometimes,Automobile,Insufficient_Weight
3,Female,21,1.52,42.00,no,yes,3.000000,1.000000,Frequently,no,1.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
4,Male,22,1.75,74.00,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,1.000000,2.000000,Sometimes,Bike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,Male,19,1.80,87.00,yes,yes,2.000000,4.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_I
419,Male,31,1.65,101.14,yes,yes,2.913452,2.269799,Sometimes,no,1.000000,no,1.889937,0.378818,no,Public_Transportation,Obesity_Type_II
420,Male,19,1.85,65.00,yes,no,2.000000,3.000000,Sometimes,no,3.000000,no,2.000000,1.000000,Sometimes,Bike,Normal_Weight
421,Male,29,1.76,113.50,yes,yes,2.320201,3.000000,Sometimes,no,2.164784,no,0.000000,1.465479,Sometimes,Automobile,Obesity_Type_II
422,Male,19,1.70,79.68,yes,no,2.735297,2.157164,Sometimes,no,1.087166,no,0.110174,0.003695,no,Public_Transportation,Overweight_Level_II

In [5]:
target = 'Obesity_level'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(1688, 17)
Obesity_level
Insufficient_Weight    221
Normal_Weight          210
Obesity_Type_I         266
Obesity_Type_II        250
Obesity_Type_III       290
Overweight_Level_I     232
Overweight_Level_II    219
dtype: int64
#####################################
Test data
(423, 17)
Obesity_level
Insufficient_Weight    56
Normal_Weight          62
Obesity_Type_I         78
Obesity_Type_II        58
Obesity_Type_III       63
Overweight_Level_I     56
Overweight_Level_II    50
dtype: int64

## 2. Pre-process training data

In [6]:
target = 'Obesity_level'
categorical_columns = ['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE','SCC','CALC','MTRANS']
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array([0, 1]), np.array([0, 1]), np.array([0, 1]), np.array([0, 1, 2, 3]), np.array([0, 1]), 
              np.array([0, 1]), np.array([0, 1, 2, 3]), np.array([0, 1, 2, 3, 4])]


data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((1688, 31), (1688,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((423, 31), (423,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = results.append(rf_results, ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.1s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.2s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.4752     0.4486  0.4752  0.4472

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = results.append(knn_results, ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.4255     0.4021  0.4255  0.4061

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = results.append(dt_results, ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.3972      0.395  0.3972  0.3926

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = results.append(svm_results, ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall     f1
0   SVM    0.2884      0.283  0.2884  0.283

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = results.append(mlp_results, ignore_index=True)
mlp_results

Iteration 1, loss = 1.97565340
Iteration 2, loss = 1.90023713
Iteration 3, loss = 1.84645470
Iteration 4, loss = 1.79401506
Iteration 5, loss = 1.73854152
Iteration 6, loss = 1.68681021
Iteration 7, loss = 1.64364092
Iteration 8, loss = 1.60663650
Iteration 9, loss = 1.58272059
Iteration 10, loss = 1.56058162
Iteration 11, loss = 1.54941529
Iteration 12, loss = 1.54071542
Iteration 13, loss = 1.52213337
Iteration 14, loss = 1.51163094
Iteration 15, loss = 1.49930773
Iteration 16, loss = 1.48995814
Iteration 17, loss = 1.47947554
Iteration 18, loss = 1.47014462
Iteration 19, loss = 1.46122386
Iteration 20, loss = 1.45192374
Iteration 21, loss = 1.44113516
Iteration 22, loss = 1.43265517
Iteration 23, loss = 1.42867517
Iteration 24, loss = 1.41531112
Iteration 25, loss = 1.41033625
Iteration 26, loss = 1.40063662
Iteration 27, loss = 1.39034347
Iteration 28, loss = 1.38183140
Iteration 29, loss = 1.37544914
Iteration 30, loss = 1.36412995
Iteration 31, loss = 1.34565564
Iteration 32, loss = 1.33865542
Iteration 33, loss = 1.33095103
Iteration 34, loss = 1.32586233
Iteration 35, loss = 1.31277141
Iteration 36, loss = 1.30509555
Iteration 37, loss = 1.29338376
Iteration 38, loss = 1.29262329
Iteration 39, loss = 1.27110268
Iteration 40, loss = 1.25882225
Iteration 41, loss = 1.24885618
Iteration 42, loss = 1.24383919
Iteration 43, loss = 1.22989853
Iteration 44, loss = 1.23372032
Iteration 45, loss = 1.22362720
Iteration 46, loss = 1.20592720
Iteration 47, loss = 1.19005775
Iteration 48, loss = 1.18214957
Iteration 49, loss = 1.17784492
Iteration 50, loss = 1.15997018
Iteration 51, loss = 1.14973335
Iteration 52, loss = 1.14157983
Iteration 53, loss = 1.13011038
Iteration 54, loss = 1.12237142
Iteration 55, loss = 1.11658930
Iteration 56, loss = 1.10398587
Iteration 57, loss = 1.09054289
Iteration 58, loss = 1.08005216
Iteration 59, loss = 1.07468299
Iteration 60, loss = 1.06786542
Iteration 61, loss = 1.05914207
Iteration 62, loss = 1.04819271
Iteration 63, loss = 1.04320311
Iteration 64, loss = 1.03178726
Iteration 65, loss = 1.01839611
Iteration 66, loss = 1.00705242
Iteration 67, loss = 0.99447981
Iteration 68, loss = 0.98526033
Iteration 69, loss = 0.97874580
Iteration 70, loss = 0.96803948
Iteration 71, loss = 0.97129534
Iteration 72, loss = 0.95592620
Iteration 73, loss = 0.94654861
Iteration 74, loss = 0.93299013
Iteration 75, loss = 0.91965879
Iteration 76, loss = 0.92099022
Iteration 77, loss = 0.91312873
Iteration 78, loss = 0.90371768
Iteration 79, loss = 0.89118117
Iteration 80, loss = 0.88943236
Iteration 81, loss = 0.87469614
Iteration 82, loss = 0.86946821
Iteration 83, loss = 0.85226714
Iteration 84, loss = 0.83995394
Iteration 85, loss = 0.83605915
Iteration 86, loss = 0.82412928
Iteration 87, loss = 0.81821323
Iteration 88, loss = 0.80785549
Iteration 89, loss = 0.79907717
Iteration 90, loss = 0.79100070
Iteration 91, loss = 0.78848285
Iteration 92, loss = 0.77900832
Iteration 93, loss = 0.76620464
Iteration 94, loss = 0.76568779
Iteration 95, loss = 0.75746562
Iteration 96, loss = 0.75175190
Iteration 97, loss = 0.74243297
Iteration 98, loss = 0.73591788
Iteration 99, loss = 0.71948640
Iteration 100, loss = 0.72879516
Iteration 101, loss = 0.71063360
Iteration 102, loss = 0.70360459
Iteration 103, loss = 0.69281330
Iteration 104, loss = 0.69062141
Iteration 105, loss = 0.69260376
Iteration 106, loss = 0.67761795
Iteration 107, loss = 0.67278893
Iteration 108, loss = 0.67057512
Iteration 109, loss = 0.64549219
Iteration 110, loss = 0.64199908
Iteration 111, loss = 0.64278789
Iteration 112, loss = 0.63619527
Iteration 113, loss = 0.63062245
Iteration 114, loss = 0.62416016
Iteration 115, loss = 0.61370478
Iteration 116, loss = 0.60385489
Iteration 117, loss = 0.59233425
Iteration 118, loss = 0.58799630
Iteration 119, loss = 0.57662345
Iteration 120, loss = 0.56765362
Iteration 121, loss = 0.56430413
Iteration 122, loss = 0.56535554
Iteration 123, loss = 0.56098466
Iteration 124, loss = 0.55497610
Iteration 125, loss = 0.54462116
Iteration 126, loss = 0.53391775
Iteration 127, loss = 0.53644262
Iteration 128, loss = 0.53022793
Iteration 129, loss = 0.52028874
Iteration 130, loss = 0.52067357
Iteration 131, loss = 0.51107388
Iteration 132, loss = 0.50450720
Iteration 133, loss = 0.48906629
Iteration 134, loss = 0.48802230
Iteration 135, loss = 0.48766383
Iteration 136, loss = 0.48084293
Iteration 137, loss = 0.46874268
Iteration 138, loss = 0.46291837
Iteration 139, loss = 0.46886380
Iteration 140, loss = 0.46237643
Iteration 141, loss = 0.45713725
Iteration 142, loss = 0.46331843
Iteration 143, loss = 0.47616391
Iteration 144, loss = 0.46582905
Iteration 145, loss = 0.45856123
Iteration 146, loss = 0.43693693
Iteration 147, loss = 0.42633035
Iteration 148, loss = 0.42341085
Iteration 149, loss = 0.40998420
Iteration 150, loss = 0.40522161
Iteration 151, loss = 0.39932392
Iteration 152, loss = 0.39842107
Iteration 153, loss = 0.38778741
Iteration 154, loss = 0.38189561
Iteration 155, loss = 0.38008321
Iteration 156, loss = 0.37772747
Iteration 157, loss = 0.37321721
Iteration 158, loss = 0.37360241
Iteration 159, loss = 0.36565833
Iteration 160, loss = 0.35579633
Iteration 161, loss = 0.35434051
Iteration 162, loss = 0.34710952
Iteration 163, loss = 0.34195077
Iteration 164, loss = 0.34182344
Iteration 165, loss = 0.34356818
Iteration 166, loss = 0.33713545
Iteration 167, loss = 0.32921922
Iteration 168, loss = 0.32011785
Iteration 169, loss = 0.31035158
Iteration 170, loss = 0.31750012
Iteration 171, loss = 0.31328258
Iteration 172, loss = 0.31114167
Iteration 173, loss = 0.30067607
Iteration 174, loss = 0.30206681
Iteration 175, loss = 0.30164805
Iteration 176, loss = 0.28790619
Iteration 177, loss = 0.28674796
Iteration 178, loss = 0.28359668
Iteration 179, loss = 0.28494617
Iteration 180, loss = 0.27824451
Iteration 181, loss = 0.27308647
Iteration 182, loss = 0.26699458
Iteration 183, loss = 0.26177614
Iteration 184, loss = 0.26151456
Iteration 185, loss = 0.26930853
Iteration 186, loss = 0.26276569
Iteration 187, loss = 0.26962393
Iteration 188, loss = 0.25742930
Iteration 189, loss = 0.24890945
Iteration 190, loss = 0.25078754
Iteration 191, loss = 0.23981520
Iteration 192, loss = 0.23507684
Iteration 193, loss = 0.23495841
Iteration 194, loss = 0.22861619
Iteration 195, loss = 0.23418941
Iteration 196, loss = 0.22940680
Iteration 197, loss = 0.22198440
Iteration 198, loss = 0.22088991
Iteration 199, loss = 0.21356706
Iteration 200, loss = 0.21494840
Iteration 201, loss = 0.20818050
Iteration 202, loss = 0.20697994
Iteration 203, loss = 0.20341986
Iteration 204, loss = 0.19689643
Iteration 205, loss = 0.19498051
Iteration 206, loss = 0.19737729
Iteration 207, loss = 0.19500714
Iteration 208, loss = 0.19334455
Iteration 209, loss = 0.18783321
Iteration 210, loss = 0.18491767
Iteration 211, loss = 0.17895935
Iteration 212, loss = 0.17633545
Iteration 213, loss = 0.18196811
Iteration 214, loss = 0.18478180
Iteration 215, loss = 0.18132634
Iteration 216, loss = 0.17283820
Iteration 217, loss = 0.17511135
Iteration 218, loss = 0.16629907
Iteration 219, loss = 0.16296195
Iteration 220, loss = 0.15726803
Iteration 221, loss = 0.15816884
Iteration 222, loss = 0.15798764
Iteration 223, loss = 0.15543748
Iteration 224, loss = 0.15186240
Iteration 225, loss = 0.14679899
Iteration 226, loss = 0.14460892
Iteration 227, loss = 0.14366482
Iteration 228, loss = 0.14252049
Iteration 229, loss = 0.13971984
Iteration 230, loss = 0.13570245
Iteration 231, loss = 0.13585089
Iteration 232, loss = 0.13591499
Iteration 233, loss = 0.13297879
Iteration 234, loss = 0.13009942
Iteration 235, loss = 0.12781541
Iteration 236, loss = 0.12623955
Iteration 237, loss = 0.12446437
Iteration 238, loss = 0.12334102
Iteration 239, loss = 0.12147676
Iteration 240, loss = 0.11904073
Iteration 241, loss = 0.11631677
Iteration 242, loss = 0.11690826
Iteration 243, loss = 0.11518406
Iteration 244, loss = 0.11461134
Iteration 245, loss = 0.11204341
Iteration 246, loss = 0.11210660
Iteration 247, loss = 0.10952231
Iteration 248, loss = 0.10735699
Iteration 249, loss = 0.10491967
Iteration 250, loss = 0.10311617
Iteration 251, loss = 0.10579442
Iteration 252, loss = 0.10912895
Iteration 253, loss = 0.10150004
Iteration 254, loss = 0.09907150
Iteration 255, loss = 0.09711618
Iteration 256, loss = 0.09727398
Iteration 257, loss = 0.09791708
Iteration 258, loss = 0.09284522
Iteration 259, loss = 0.09195249
Iteration 260, loss = 0.08902233
Iteration 261, loss = 0.08838016
Iteration 262, loss = 0.08555536
Iteration 263, loss = 0.08810255
Iteration 264, loss = 0.09243935
Iteration 265, loss = 0.09073968
Iteration 266, loss = 0.08568783
Iteration 267, loss = 0.08508748
Iteration 268, loss = 0.08831792
Iteration 269, loss = 0.08741168
Iteration 270, loss = 0.08216484
Iteration 271, loss = 0.07845640
Iteration 272, loss = 0.07717620
Iteration 273, loss = 0.07684351
Iteration 274, loss = 0.07693324
Iteration 275, loss = 0.07962689
Iteration 276, loss = 0.07427143
Iteration 277, loss = 0.07452460
Iteration 278, loss = 0.07053200
Iteration 279, loss = 0.06837415
Iteration 280, loss = 0.06769518
Iteration 281, loss = 0.06662430
Iteration 282, loss = 0.06693907
Iteration 283, loss = 0.06500133
Iteration 284, loss = 0.06591338
Iteration 285, loss = 0.06449333
Iteration 286, loss = 0.06319448
Iteration 287, loss = 0.06295757
Iteration 288, loss = 0.06459518
Iteration 289, loss = 0.06500939
Iteration 290, loss = 0.06214245
Iteration 291, loss = 0.06337656
Iteration 292, loss = 0.06145254
Iteration 293, loss = 0.05973622
Iteration 294, loss = 0.05755982
Iteration 295, loss = 0.05512376
Iteration 296, loss = 0.05599797
Iteration 297, loss = 0.05651124
Iteration 298, loss = 0.05495199
Iteration 299, loss = 0.05317735
Iteration 300, loss = 0.05073335

  model  accuracy  precision  recall      f1
0   MLP    0.4043     0.3893  0.4043  0.3947

## 9. Save results file

In [14]:
results.to_csv('RESULTS/models_results_gm.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.4752     0.4486  0.4752  0.4472
1   KNN    0.4255     0.4021  0.4255  0.4061
2    DT    0.3972     0.3950  0.3972  0.3926
3   SVM    0.2884     0.2830  0.2884  0.2830
4   MLP    0.4043     0.3893  0.4043  0.3947