# TSTR SDV Dataset C - Obesity

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
HOME_PATH = '' #home path of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(HOME_PATH + 'SYNTHETIC DATASETS/SDV/C_Obesity_Data_Synthetic_SDV.csv')
categorical_columns = ['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE','SCC','CALC','MTRANS','Obesity_level']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_level
0,Male,28,1.76,123.43,yes,yes,3.205596,2.903116,Sometimes,no,1.904073,no,0.448286,0.313930,Sometimes,Public_Transportation,Obesity_Type_II
1,Male,12,1.69,40.75,yes,yes,2.239509,2.653353,Sometimes,no,2.042313,no,0.645014,0.601065,no,Public_Transportation,Overweight_Level_I
2,Female,18,1.63,94.78,yes,yes,3.094983,3.169795,Sometimes,no,2.692556,no,1.037283,0.856946,Sometimes,Public_Transportation,Overweight_Level_I
3,Male,21,1.82,137.00,no,yes,2.095592,3.177185,Sometimes,no,2.276122,no,1.221715,0.845391,Sometimes,Public_Transportation,Obesity_Type_I
4,Female,38,1.65,84.02,yes,yes,2.726584,1.015046,Sometimes,no,0.278486,no,1.055731,0.248985,no,Public_Transportation,Obesity_Type_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Male,31,1.48,76.02,yes,yes,2.602491,3.355760,Sometimes,no,2.240679,no,1.903530,0.172436,Sometimes,Public_Transportation,Overweight_Level_II
1684,Female,21,1.67,45.28,yes,yes,2.534703,3.542202,Sometimes,no,1.935781,no,-0.184959,0.306923,Sometimes,Public_Transportation,Normal_Weight
1685,Male,32,1.69,103.85,yes,yes,2.682470,2.334944,Sometimes,no,3.093748,no,1.181994,0.758202,Sometimes,Public_Transportation,Obesity_Type_I
1686,Male,22,1.77,115.65,yes,yes,3.076754,3.583925,Sometimes,no,2.792898,no,1.703388,1.141771,Sometimes,Public_Transportation,Obesity_Type_II
1687,Female,30,1.56,80.21,yes,yes,2.743709,3.437653,Sometimes,no,2.086823,no,0.345362,0.778831,Sometimes,Public_Transportation,Obesity_Type_III

In [4]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'REAL DATASETS/TEST DATASETS/C_Obesity_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_level
0,Female,20,1.76,53.70,yes,yes,2.000000,3.891994,Frequently,no,1.863930,no,2.870127,2.000000,no,Public_Transportation,Insufficient_Weight
1,Female,26,1.62,111.00,yes,yes,3.000000,3.000000,Sometimes,no,2.704315,no,0.000000,0.322666,Sometimes,Public_Transportation,Obesity_Type_III
2,Male,18,1.85,60.00,yes,yes,3.000000,4.000000,Sometimes,no,2.000000,yes,2.000000,0.000000,Sometimes,Automobile,Insufficient_Weight
3,Female,21,1.52,42.00,no,yes,3.000000,1.000000,Frequently,no,1.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
4,Male,22,1.75,74.00,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,1.000000,2.000000,Sometimes,Bike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,Male,19,1.80,87.00,yes,yes,2.000000,4.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_I
419,Male,31,1.65,101.14,yes,yes,2.913452,2.269799,Sometimes,no,1.000000,no,1.889937,0.378818,no,Public_Transportation,Obesity_Type_II
420,Male,19,1.85,65.00,yes,no,2.000000,3.000000,Sometimes,no,3.000000,no,2.000000,1.000000,Sometimes,Bike,Normal_Weight
421,Male,29,1.76,113.50,yes,yes,2.320201,3.000000,Sometimes,no,2.164784,no,0.000000,1.465479,Sometimes,Automobile,Obesity_Type_II
422,Male,19,1.70,79.68,yes,no,2.735297,2.157164,Sometimes,no,1.087166,no,0.110174,0.003695,no,Public_Transportation,Overweight_Level_II

In [5]:
target = 'Obesity_level'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(1688, 17)
Obesity_level
Insufficient_Weight    135
Normal_Weight          203
Obesity_Type_I         185
Obesity_Type_II        311
Obesity_Type_III       267
Overweight_Level_I     297
Overweight_Level_II    290
dtype: int64
#####################################
Test data
(423, 17)
Obesity_level
Insufficient_Weight    56
Normal_Weight          62
Obesity_Type_I         78
Obesity_Type_II        58
Obesity_Type_III       63
Overweight_Level_I     56
Overweight_Level_II    50
dtype: int64

## 2. Pre-process training data

In [6]:
target = 'Obesity_level'
categorical_columns = ['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE','SCC','CALC','MTRANS']
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array([0, 1]), np.array([0, 1]), np.array([0, 1]), np.array([0, 1, 2, 3]), np.array([0, 1]), 
              np.array([0, 1]), np.array([0, 1, 2, 3]), np.array([0, 1, 2, 3, 4])]


data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((1688, 31), (1688,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((423, 31), (423,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = results.append(rf_results, ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.1s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.2s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall     f1
0    RF    0.1702     0.2082  0.1702  0.175

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = results.append(knn_results, ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.1513     0.1667  0.1513  0.1502

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = results.append(dt_results, ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.1915     0.2394  0.1915  0.2069

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = results.append(svm_results, ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall      f1
0   SVM    0.1702     0.1973  0.1702  0.1665

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = results.append(mlp_results, ignore_index=True)
mlp_results

Iteration 1, loss = 1.98768556
Iteration 2, loss = 1.91251759
Iteration 3, loss = 1.89066202
Iteration 4, loss = 1.86943417
Iteration 5, loss = 1.84944906
Iteration 6, loss = 1.82883847
Iteration 7, loss = 1.80722832
Iteration 8, loss = 1.78624045
Iteration 9, loss = 1.76701335
Iteration 10, loss = 1.74486098
Iteration 11, loss = 1.72592534
Iteration 12, loss = 1.71056509
Iteration 13, loss = 1.69266133
Iteration 14, loss = 1.68214506
Iteration 15, loss = 1.66310682
Iteration 16, loss = 1.64686186
Iteration 17, loss = 1.63708379
Iteration 18, loss = 1.62216268
Iteration 19, loss = 1.61024017
Iteration 20, loss = 1.60407851
Iteration 21, loss = 1.58635509
Iteration 22, loss = 1.58079131
Iteration 23, loss = 1.56837718
Iteration 24, loss = 1.55490047
Iteration 25, loss = 1.54824971
Iteration 26, loss = 1.53653047
Iteration 27, loss = 1.52243205
Iteration 28, loss = 1.51201122
Iteration 29, loss = 1.50651508
Iteration 30, loss = 1.49880188
Iteration 31, loss = 1.48424175
Iteration 32, loss = 1.47560987
Iteration 33, loss = 1.46439250
Iteration 34, loss = 1.45635067
Iteration 35, loss = 1.44602695
Iteration 36, loss = 1.43547638
Iteration 37, loss = 1.42342723
Iteration 38, loss = 1.41208077
Iteration 39, loss = 1.40037407
Iteration 40, loss = 1.39498264
Iteration 41, loss = 1.38932707
Iteration 42, loss = 1.38457166
Iteration 43, loss = 1.36795763
Iteration 44, loss = 1.35435353
Iteration 45, loss = 1.34801073
Iteration 46, loss = 1.34763890
Iteration 47, loss = 1.32853227
Iteration 48, loss = 1.32466012
Iteration 49, loss = 1.31456114
Iteration 50, loss = 1.29676908
Iteration 51, loss = 1.29125738
Iteration 52, loss = 1.27626491
Iteration 53, loss = 1.27037948
Iteration 54, loss = 1.26476215
Iteration 55, loss = 1.25260182
Iteration 56, loss = 1.24218240
Iteration 57, loss = 1.23888371
Iteration 58, loss = 1.23262358
Iteration 59, loss = 1.22306848
Iteration 60, loss = 1.21174699
Iteration 61, loss = 1.19640641
Iteration 62, loss = 1.18916918
Iteration 63, loss = 1.18249445
Iteration 64, loss = 1.17351840
Iteration 65, loss = 1.16225474
Iteration 66, loss = 1.16339215
Iteration 67, loss = 1.14362999
Iteration 68, loss = 1.13497361
Iteration 69, loss = 1.13314043
Iteration 70, loss = 1.11421044
Iteration 71, loss = 1.10969966
Iteration 72, loss = 1.10164019
Iteration 73, loss = 1.08690501
Iteration 74, loss = 1.08461450
Iteration 75, loss = 1.08302071
Iteration 76, loss = 1.07839066
Iteration 77, loss = 1.06745001
Iteration 78, loss = 1.05177911
Iteration 79, loss = 1.04615780
Iteration 80, loss = 1.03067879
Iteration 81, loss = 1.02573106
Iteration 82, loss = 1.01531153
Iteration 83, loss = 1.00823228
Iteration 84, loss = 1.01602383
Iteration 85, loss = 1.00165119
Iteration 86, loss = 0.99530080
Iteration 87, loss = 0.98253319
Iteration 88, loss = 0.96385535
Iteration 89, loss = 0.96199757
Iteration 90, loss = 0.95197394
Iteration 91, loss = 0.94841007
Iteration 92, loss = 0.93705016
Iteration 93, loss = 0.92898328
Iteration 94, loss = 0.91816074
Iteration 95, loss = 0.90970139
Iteration 96, loss = 0.90784129
Iteration 97, loss = 0.90196512
Iteration 98, loss = 0.89434467
Iteration 99, loss = 0.89545339
Iteration 100, loss = 0.87451574
Iteration 101, loss = 0.86931348
Iteration 102, loss = 0.86838546
Iteration 103, loss = 0.86511033
Iteration 104, loss = 0.85087972
Iteration 105, loss = 0.84673346
Iteration 106, loss = 0.83015661
Iteration 107, loss = 0.83001724
Iteration 108, loss = 0.82355661
Iteration 109, loss = 0.80938628
Iteration 110, loss = 0.80653403
Iteration 111, loss = 0.79687492
Iteration 112, loss = 0.79040035
Iteration 113, loss = 0.78091712
Iteration 114, loss = 0.77483936
Iteration 115, loss = 0.76307593
Iteration 116, loss = 0.75890715
Iteration 117, loss = 0.75181314
Iteration 118, loss = 0.76034226
Iteration 119, loss = 0.75655860
Iteration 120, loss = 0.72921969
Iteration 121, loss = 0.72641467
Iteration 122, loss = 0.73035828
Iteration 123, loss = 0.72103947
Iteration 124, loss = 0.71136683
Iteration 125, loss = 0.70115370
Iteration 126, loss = 0.69776943
Iteration 127, loss = 0.68933339
Iteration 128, loss = 0.67969793
Iteration 129, loss = 0.68089867
Iteration 130, loss = 0.66798472
Iteration 131, loss = 0.66619674
Iteration 132, loss = 0.66099941
Iteration 133, loss = 0.65623594
Iteration 134, loss = 0.65661380
Iteration 135, loss = 0.64795038
Iteration 136, loss = 0.64601079
Iteration 137, loss = 0.62882609
Iteration 138, loss = 0.63010196
Iteration 139, loss = 0.61103745
Iteration 140, loss = 0.61556041
Iteration 141, loss = 0.61211755
Iteration 142, loss = 0.60073135
Iteration 143, loss = 0.59785559
Iteration 144, loss = 0.59383499
Iteration 145, loss = 0.58739784
Iteration 146, loss = 0.58304725
Iteration 147, loss = 0.57191485
Iteration 148, loss = 0.56286158
Iteration 149, loss = 0.56188404
Iteration 150, loss = 0.55009220
Iteration 151, loss = 0.54483808
Iteration 152, loss = 0.54222224
Iteration 153, loss = 0.53658486
Iteration 154, loss = 0.54085757
Iteration 155, loss = 0.53417143
Iteration 156, loss = 0.54285223
Iteration 157, loss = 0.52405984
Iteration 158, loss = 0.51406290
Iteration 159, loss = 0.51608328
Iteration 160, loss = 0.50336300
Iteration 161, loss = 0.51177664
Iteration 162, loss = 0.48725673
Iteration 163, loss = 0.48242498
Iteration 164, loss = 0.47670146
Iteration 165, loss = 0.47602796
Iteration 166, loss = 0.47190199
Iteration 167, loss = 0.46991526
Iteration 168, loss = 0.47078141
Iteration 169, loss = 0.45997967
Iteration 170, loss = 0.45198307
Iteration 171, loss = 0.44918050
Iteration 172, loss = 0.46155340
Iteration 173, loss = 0.44410905
Iteration 174, loss = 0.44301063
Iteration 175, loss = 0.43824260
Iteration 176, loss = 0.42975010
Iteration 177, loss = 0.42745162
Iteration 178, loss = 0.41636995
Iteration 179, loss = 0.41170958
Iteration 180, loss = 0.40696810
Iteration 181, loss = 0.40563202
Iteration 182, loss = 0.40085720
Iteration 183, loss = 0.40124487
Iteration 184, loss = 0.39524583
Iteration 185, loss = 0.39297295
Iteration 186, loss = 0.38841326
Iteration 187, loss = 0.38162150
Iteration 188, loss = 0.37380604
Iteration 189, loss = 0.36510812
Iteration 190, loss = 0.37039896
Iteration 191, loss = 0.36302793
Iteration 192, loss = 0.35900747
Iteration 193, loss = 0.36026718
Iteration 194, loss = 0.36256576
Iteration 195, loss = 0.36812604
Iteration 196, loss = 0.36381880
Iteration 197, loss = 0.35687978
Iteration 198, loss = 0.34291370
Iteration 199, loss = 0.33323407
Iteration 200, loss = 0.33027079
Iteration 201, loss = 0.32146454
Iteration 202, loss = 0.31782221
Iteration 203, loss = 0.31473810
Iteration 204, loss = 0.32400116
Iteration 205, loss = 0.31100364
Iteration 206, loss = 0.30687371
Iteration 207, loss = 0.30919375
Iteration 208, loss = 0.30714549
Iteration 209, loss = 0.30371613
Iteration 210, loss = 0.29971883
Iteration 211, loss = 0.29101855
Iteration 212, loss = 0.28512550
Iteration 213, loss = 0.28273905
Iteration 214, loss = 0.28030965
Iteration 215, loss = 0.27692043
Iteration 216, loss = 0.27977138
Iteration 217, loss = 0.27797325
Iteration 218, loss = 0.26801626
Iteration 219, loss = 0.26212091
Iteration 220, loss = 0.26871504
Iteration 221, loss = 0.25949437
Iteration 222, loss = 0.25236437
Iteration 223, loss = 0.25223888
Iteration 224, loss = 0.25591783
Iteration 225, loss = 0.24540934
Iteration 226, loss = 0.24812614
Iteration 227, loss = 0.25060688
Iteration 228, loss = 0.25292642
Iteration 229, loss = 0.24048871
Iteration 230, loss = 0.23945149
Iteration 231, loss = 0.23578227
Iteration 232, loss = 0.22899874
Iteration 233, loss = 0.22591479
Iteration 234, loss = 0.22039871
Iteration 235, loss = 0.22152444
Iteration 236, loss = 0.21854281
Iteration 237, loss = 0.21379416
Iteration 238, loss = 0.21094766
Iteration 239, loss = 0.21042034
Iteration 240, loss = 0.21180040
Iteration 241, loss = 0.20798729
Iteration 242, loss = 0.20035061
Iteration 243, loss = 0.19777664
Iteration 244, loss = 0.19762202
Iteration 245, loss = 0.19857430
Iteration 246, loss = 0.19430758
Iteration 247, loss = 0.18818136
Iteration 248, loss = 0.19359059
Iteration 249, loss = 0.19279985
Iteration 250, loss = 0.18738274
Iteration 251, loss = 0.18290114
Iteration 252, loss = 0.18092815
Iteration 253, loss = 0.17377890
Iteration 254, loss = 0.17935469
Iteration 255, loss = 0.18123901
Iteration 256, loss = 0.17457759
Iteration 257, loss = 0.17664846
Iteration 258, loss = 0.17538999
Iteration 259, loss = 0.16886971
Iteration 260, loss = 0.16644417
Iteration 261, loss = 0.16430180
Iteration 262, loss = 0.15759064
Iteration 263, loss = 0.15475316
Iteration 264, loss = 0.15299118
Iteration 265, loss = 0.15405532
Iteration 266, loss = 0.14842620
Iteration 267, loss = 0.14912844
Iteration 268, loss = 0.14859278
Iteration 269, loss = 0.14519363
Iteration 270, loss = 0.14122121
Iteration 271, loss = 0.14060826
Iteration 272, loss = 0.14153579
Iteration 273, loss = 0.14011062
Iteration 274, loss = 0.13897745
Iteration 275, loss = 0.13869756
Iteration 276, loss = 0.13703995
Iteration 277, loss = 0.13669012
Iteration 278, loss = 0.13218989
Iteration 279, loss = 0.13245994
Iteration 280, loss = 0.12945020
Iteration 281, loss = 0.13206420
Iteration 282, loss = 0.13079543
Iteration 283, loss = 0.12695704
Iteration 284, loss = 0.12378731
Iteration 285, loss = 0.12677431
Iteration 286, loss = 0.12520195
Iteration 287, loss = 0.11991108
Iteration 288, loss = 0.11732294
Iteration 289, loss = 0.11367864
Iteration 290, loss = 0.11220488
Iteration 291, loss = 0.10948789
Iteration 292, loss = 0.10853457
Iteration 293, loss = 0.10716554
Iteration 294, loss = 0.10724554
Iteration 295, loss = 0.10154611
Iteration 296, loss = 0.10026988
Iteration 297, loss = 0.09849673
Iteration 298, loss = 0.09852446
Iteration 299, loss = 0.10081874
Iteration 300, loss = 0.10026985

  model  accuracy  precision  recall      f1
0   MLP    0.1939     0.1907  0.1939  0.1769

## 9. Save results file

In [14]:
results.to_csv('RESULTS/models_results_sdv.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.1702     0.2082  0.1702  0.1750
1   KNN    0.1513     0.1667  0.1513  0.1502
2    DT    0.1915     0.2394  0.1915  0.2069
3   SVM    0.1702     0.1973  0.1702  0.1665
4   MLP    0.1939     0.1907  0.1939  0.1769