# TSTR CTGAN Dataset C - Obesity

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
HOME_PATH = '' #home path of the project
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(HOME_PATH + 'SYNTHETIC DATASETS/CTGAN/C_Obesity_Data_Synthetic_CTGAN.csv')
categorical_columns = ['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE','SCC','CALC','MTRANS','Obesity_level']
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_level
0,Male,22,1.615909,70.916647,no,yes,2.941627,0.969111,Sometimes,no,0.913025,no,1.421292,1.960299,Frequently,Public_Transportation,Overweight_Level_II
1,Male,19,1.627690,38.963229,yes,yes,1.482722,3.557708,Sometimes,no,1.172519,no,0.823106,0.074333,Sometimes,Bike,Overweight_Level_I
2,Female,23,1.651837,39.270701,yes,no,2.277436,3.104416,Frequently,no,2.970412,no,0.830696,0.817655,Sometimes,Automobile,Obesity_Type_II
3,Male,39,1.599153,53.385542,yes,yes,2.000000,2.925327,Sometimes,no,1.171034,no,1.566050,0.743011,no,Automobile,Overweight_Level_I
4,Male,25,1.772736,37.032741,yes,yes,2.244654,2.937739,Sometimes,no,1.965131,no,0.050090,1.020689,Sometimes,Public_Transportation,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1683,Male,24,1.655055,59.147433,yes,yes,2.000000,2.984288,Sometimes,no,1.860131,no,-0.009217,1.041798,Sometimes,Automobile,Insufficient_Weight
1684,Male,26,1.471980,39.273362,yes,yes,3.000000,2.958333,Sometimes,no,1.931936,no,0.845779,0.178117,Sometimes,Public_Transportation,Obesity_Type_II
1685,Male,26,1.757607,73.089889,no,yes,2.886260,3.000137,no,no,1.888656,no,-0.001930,0.126523,Sometimes,Public_Transportation,Insufficient_Weight
1686,Female,25,1.843430,88.362564,no,yes,2.000000,2.934632,Sometimes,no,1.722676,no,2.120414,0.069274,Sometimes,Public_Transportation,Insufficient_Weight
1687,Male,22,1.661903,57.925314,no,yes,3.000000,3.012509,Sometimes,no,1.934231,no,0.784658,0.034025,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'REAL DATASETS/TEST DATASETS/C_Obesity_Data_Real_Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_level
0,Female,20,1.76,53.70,yes,yes,2.000000,3.891994,Frequently,no,1.863930,no,2.870127,2.000000,no,Public_Transportation,Insufficient_Weight
1,Female,26,1.62,111.00,yes,yes,3.000000,3.000000,Sometimes,no,2.704315,no,0.000000,0.322666,Sometimes,Public_Transportation,Obesity_Type_III
2,Male,18,1.85,60.00,yes,yes,3.000000,4.000000,Sometimes,no,2.000000,yes,2.000000,0.000000,Sometimes,Automobile,Insufficient_Weight
3,Female,21,1.52,42.00,no,yes,3.000000,1.000000,Frequently,no,1.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Insufficient_Weight
4,Male,22,1.75,74.00,yes,no,2.000000,3.000000,Sometimes,no,2.000000,no,1.000000,2.000000,Sometimes,Bike,Normal_Weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,Male,19,1.80,87.00,yes,yes,2.000000,4.000000,Sometimes,no,2.000000,no,2.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_I
419,Male,31,1.65,101.14,yes,yes,2.913452,2.269799,Sometimes,no,1.000000,no,1.889937,0.378818,no,Public_Transportation,Obesity_Type_II
420,Male,19,1.85,65.00,yes,no,2.000000,3.000000,Sometimes,no,3.000000,no,2.000000,1.000000,Sometimes,Bike,Normal_Weight
421,Male,29,1.76,113.50,yes,yes,2.320201,3.000000,Sometimes,no,2.164784,no,0.000000,1.465479,Sometimes,Automobile,Obesity_Type_II
422,Male,19,1.70,79.68,yes,no,2.735297,2.157164,Sometimes,no,1.087166,no,0.110174,0.003695,no,Public_Transportation,Overweight_Level_II

In [5]:
target = 'Obesity_level'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(1688, 17)
Obesity_level
Insufficient_Weight    214
Normal_Weight          189
Obesity_Type_I         198
Obesity_Type_II        117
Obesity_Type_III       177
Overweight_Level_I     363
Overweight_Level_II    430
dtype: int64
#####################################
Test data
(423, 17)
Obesity_level
Insufficient_Weight    56
Normal_Weight          62
Obesity_Type_I         78
Obesity_Type_II        58
Obesity_Type_III       63
Overweight_Level_I     56
Overweight_Level_II    50
dtype: int64

## 2. Pre-process training data

In [6]:
target = 'Obesity_level'
categorical_columns = ['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE','SCC','CALC','MTRANS']
numerical_columns = train_data.select_dtypes(include=['int64','float64']).columns.tolist()
categories = [np.array([0, 1]), np.array([0, 1]), np.array([0, 1]), np.array([0, 1, 2, 3]), np.array([0, 1]), 
              np.array([0, 1]), np.array([0, 1, 2, 3]), np.array([0, 1, 2, 3, 4])]


data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((1688, 31), (1688,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((423, 31), (423,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = results.append(rf_results, ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.1s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.2s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.0733     0.0476  0.0733  0.0519

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = results.append(knn_results, ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN      0.13      0.127    0.13  0.1212

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = results.append(dt_results, ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.0449     0.0708  0.0449  0.0486

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = results.append(svm_results, ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall     f1
0   SVM     0.156     0.1303   0.156  0.133

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = results.append(mlp_results, ignore_index=True)
mlp_results

Iteration 1, loss = 1.95838111
Iteration 2, loss = 1.87429474
Iteration 3, loss = 1.84293801
Iteration 4, loss = 1.82549634
Iteration 5, loss = 1.81202389
Iteration 6, loss = 1.79542923
Iteration 7, loss = 1.78155943
Iteration 8, loss = 1.76632824
Iteration 9, loss = 1.75062910
Iteration 10, loss = 1.73652795
Iteration 11, loss = 1.71890767
Iteration 12, loss = 1.70397853
Iteration 13, loss = 1.68463086
Iteration 14, loss = 1.66743618
Iteration 15, loss = 1.65092127
Iteration 16, loss = 1.63351975
Iteration 17, loss = 1.61945710
Iteration 18, loss = 1.60144509
Iteration 19, loss = 1.59198286
Iteration 20, loss = 1.57786315
Iteration 21, loss = 1.56063463
Iteration 22, loss = 1.54128107
Iteration 23, loss = 1.52461815
Iteration 24, loss = 1.50881444
Iteration 25, loss = 1.49150214
Iteration 26, loss = 1.48162910
Iteration 27, loss = 1.46236245
Iteration 28, loss = 1.44994710
Iteration 29, loss = 1.43277369
Iteration 30, loss = 1.41094266
Iteration 31, loss = 1.39620726
Iteration 32, loss = 1.37684700
Iteration 33, loss = 1.36702673
Iteration 34, loss = 1.34532081
Iteration 35, loss = 1.33218610
Iteration 36, loss = 1.31890935
Iteration 37, loss = 1.30280352
Iteration 38, loss = 1.28898319
Iteration 39, loss = 1.26702029
Iteration 40, loss = 1.25119502
Iteration 41, loss = 1.23428820
Iteration 42, loss = 1.21768866
Iteration 43, loss = 1.20257728
Iteration 44, loss = 1.19044183
Iteration 45, loss = 1.16982280
Iteration 46, loss = 1.15993719
Iteration 47, loss = 1.15740594
Iteration 48, loss = 1.14443888
Iteration 49, loss = 1.11967672
Iteration 50, loss = 1.10262966
Iteration 51, loss = 1.07855682
Iteration 52, loss = 1.06872211
Iteration 53, loss = 1.05064176
Iteration 54, loss = 1.03841937
Iteration 55, loss = 1.02417193
Iteration 56, loss = 1.01714306
Iteration 57, loss = 0.99657672
Iteration 58, loss = 0.98086960
Iteration 59, loss = 0.96653862
Iteration 60, loss = 0.95068339
Iteration 61, loss = 0.95397532
Iteration 62, loss = 0.93240629
Iteration 63, loss = 0.92316238
Iteration 64, loss = 0.91189121
Iteration 65, loss = 0.89843724
Iteration 66, loss = 0.87912942
Iteration 67, loss = 0.87523855
Iteration 68, loss = 0.86143818
Iteration 69, loss = 0.84254970
Iteration 70, loss = 0.84673371
Iteration 71, loss = 0.82946930
Iteration 72, loss = 0.81730388
Iteration 73, loss = 0.79984091
Iteration 74, loss = 0.78311443
Iteration 75, loss = 0.78103984
Iteration 76, loss = 0.75873688
Iteration 77, loss = 0.74980312
Iteration 78, loss = 0.74082630
Iteration 79, loss = 0.73364653
Iteration 80, loss = 0.71189483
Iteration 81, loss = 0.71143315
Iteration 82, loss = 0.70217063
Iteration 83, loss = 0.68423466
Iteration 84, loss = 0.67606312
Iteration 85, loss = 0.66466012
Iteration 86, loss = 0.65682991
Iteration 87, loss = 0.64316736
Iteration 88, loss = 0.63364722
Iteration 89, loss = 0.63480778
Iteration 90, loss = 0.62839923
Iteration 91, loss = 0.61548698
Iteration 92, loss = 0.60555048
Iteration 93, loss = 0.60223251
Iteration 94, loss = 0.60542767
Iteration 95, loss = 0.59738616
Iteration 96, loss = 0.57385892
Iteration 97, loss = 0.57329242
Iteration 98, loss = 0.56642193
Iteration 99, loss = 0.55767603
Iteration 100, loss = 0.54950467
Iteration 101, loss = 0.53679661
Iteration 102, loss = 0.54371166
Iteration 103, loss = 0.53105011
Iteration 104, loss = 0.51372663
Iteration 105, loss = 0.50474746
Iteration 106, loss = 0.50072947
Iteration 107, loss = 0.49074579
Iteration 108, loss = 0.47894488
Iteration 109, loss = 0.47168236
Iteration 110, loss = 0.47084691
Iteration 111, loss = 0.46976713
Iteration 112, loss = 0.45957991
Iteration 113, loss = 0.45522398
Iteration 114, loss = 0.44563339
Iteration 115, loss = 0.44450739
Iteration 116, loss = 0.44205252
Iteration 117, loss = 0.42967218
Iteration 118, loss = 0.42799478
Iteration 119, loss = 0.42285162
Iteration 120, loss = 0.41775797
Iteration 121, loss = 0.40995227
Iteration 122, loss = 0.40053931
Iteration 123, loss = 0.39537073
Iteration 124, loss = 0.38254848
Iteration 125, loss = 0.37808019
Iteration 126, loss = 0.37688963
Iteration 127, loss = 0.37211932
Iteration 128, loss = 0.36426554
Iteration 129, loss = 0.36304812
Iteration 130, loss = 0.35466033
Iteration 131, loss = 0.35599425
Iteration 132, loss = 0.34999068
Iteration 133, loss = 0.34577120
Iteration 134, loss = 0.34053486
Iteration 135, loss = 0.33357663
Iteration 136, loss = 0.32637912
Iteration 137, loss = 0.32358919
Iteration 138, loss = 0.31999227
Iteration 139, loss = 0.31988704
Iteration 140, loss = 0.30931111
Iteration 141, loss = 0.30482140
Iteration 142, loss = 0.29824570
Iteration 143, loss = 0.29601383
Iteration 144, loss = 0.29292362
Iteration 145, loss = 0.28424510
Iteration 146, loss = 0.28175043
Iteration 147, loss = 0.27485693
Iteration 148, loss = 0.27143430
Iteration 149, loss = 0.27457128
Iteration 150, loss = 0.27422817
Iteration 151, loss = 0.26582498
Iteration 152, loss = 0.26108979
Iteration 153, loss = 0.26072803
Iteration 154, loss = 0.25873402
Iteration 155, loss = 0.25613790
Iteration 156, loss = 0.25189162
Iteration 157, loss = 0.24813163
Iteration 158, loss = 0.24340873
Iteration 159, loss = 0.24359535
Iteration 160, loss = 0.24777771
Iteration 161, loss = 0.23037332
Iteration 162, loss = 0.22456006
Iteration 163, loss = 0.22178238
Iteration 164, loss = 0.21587409
Iteration 165, loss = 0.21026327
Iteration 166, loss = 0.20817006
Iteration 167, loss = 0.21340989
Iteration 168, loss = 0.21590304
Iteration 169, loss = 0.20826867
Iteration 170, loss = 0.20159153
Iteration 171, loss = 0.19468913
Iteration 172, loss = 0.19654952
Iteration 173, loss = 0.19468549
Iteration 174, loss = 0.18864959
Iteration 175, loss = 0.18321496
Iteration 176, loss = 0.18320413
Iteration 177, loss = 0.18270854
Iteration 178, loss = 0.17956643
Iteration 179, loss = 0.17635907
Iteration 180, loss = 0.17396517
Iteration 181, loss = 0.17666878
Iteration 182, loss = 0.16644781
Iteration 183, loss = 0.17449233
Iteration 184, loss = 0.16715110
Iteration 185, loss = 0.16131188
Iteration 186, loss = 0.15866824
Iteration 187, loss = 0.15558580
Iteration 188, loss = 0.15325799
Iteration 189, loss = 0.14658776
Iteration 190, loss = 0.15037984
Iteration 191, loss = 0.14482247
Iteration 192, loss = 0.14089367
Iteration 193, loss = 0.14167202
Iteration 194, loss = 0.13913200
Iteration 195, loss = 0.13373985
Iteration 196, loss = 0.13357492
Iteration 197, loss = 0.13257093
Iteration 198, loss = 0.12940168
Iteration 199, loss = 0.13247853
Iteration 200, loss = 0.13029376
Iteration 201, loss = 0.13221966
Iteration 202, loss = 0.12294752
Iteration 203, loss = 0.12109876
Iteration 204, loss = 0.11948712
Iteration 205, loss = 0.12064428
Iteration 206, loss = 0.11530271
Iteration 207, loss = 0.12295420
Iteration 208, loss = 0.11718119
Iteration 209, loss = 0.11102664
Iteration 210, loss = 0.11447961
Iteration 211, loss = 0.11336138
Iteration 212, loss = 0.10899111
Iteration 213, loss = 0.10757472
Iteration 214, loss = 0.10523416
Iteration 215, loss = 0.10805917
Iteration 216, loss = 0.11278917
Iteration 217, loss = 0.10145353
Iteration 218, loss = 0.09770267
Iteration 219, loss = 0.09250049
Iteration 220, loss = 0.09134405
Iteration 221, loss = 0.09070302
Iteration 222, loss = 0.08954907
Iteration 223, loss = 0.08860328
Iteration 224, loss = 0.09057668
Iteration 225, loss = 0.08961778
Iteration 226, loss = 0.08683697
Iteration 227, loss = 0.08526953
Iteration 228, loss = 0.08231479
Iteration 229, loss = 0.08129431
Iteration 230, loss = 0.08344452
Iteration 231, loss = 0.08016681
Iteration 232, loss = 0.07913039
Iteration 233, loss = 0.07625907
Iteration 234, loss = 0.07517526
Iteration 235, loss = 0.07697923
Iteration 236, loss = 0.07959867
Iteration 237, loss = 0.07924275
Iteration 238, loss = 0.07836007
Iteration 239, loss = 0.07652519
Iteration 240, loss = 0.07482111
Iteration 241, loss = 0.06883441
Iteration 242, loss = 0.06665324
Iteration 243, loss = 0.06421416
Iteration 244, loss = 0.06511173
Iteration 245, loss = 0.06235412
Iteration 246, loss = 0.06294517
Iteration 247, loss = 0.06137721
Iteration 248, loss = 0.05921297
Iteration 249, loss = 0.05847013
Iteration 250, loss = 0.05855610
Iteration 251, loss = 0.05839893
Iteration 252, loss = 0.05863885
Iteration 253, loss = 0.06382419
Iteration 254, loss = 0.05745604
Iteration 255, loss = 0.05625368
Iteration 256, loss = 0.05483668
Iteration 257, loss = 0.05317119
Iteration 258, loss = 0.05247804
Iteration 259, loss = 0.05164171
Iteration 260, loss = 0.05053104
Iteration 261, loss = 0.05048772
Iteration 262, loss = 0.04999385
Iteration 263, loss = 0.04868172
Iteration 264, loss = 0.04769488
Iteration 265, loss = 0.04712433
Iteration 266, loss = 0.04749987
Iteration 267, loss = 0.04722488
Iteration 268, loss = 0.04908064
Iteration 269, loss = 0.04716129
Iteration 270, loss = 0.04728429
Iteration 271, loss = 0.04551403
Iteration 272, loss = 0.04358732
Iteration 273, loss = 0.04332407
Iteration 274, loss = 0.04248363
Iteration 275, loss = 0.04348466
Iteration 276, loss = 0.04607886
Iteration 277, loss = 0.04124499
Iteration 278, loss = 0.04300539
Iteration 279, loss = 0.03949549
Iteration 280, loss = 0.03861676
Iteration 281, loss = 0.04005965
Iteration 282, loss = 0.03869454
Iteration 283, loss = 0.03660248
Iteration 284, loss = 0.03601724
Iteration 285, loss = 0.03506653
Iteration 286, loss = 0.03418181
Iteration 287, loss = 0.03405779
Iteration 288, loss = 0.03427369
Iteration 289, loss = 0.03393142
Iteration 290, loss = 0.03327798
Iteration 291, loss = 0.03222400
Iteration 292, loss = 0.03294089
Iteration 293, loss = 0.03201329
Iteration 294, loss = 0.03096550
Iteration 295, loss = 0.03136486
Iteration 296, loss = 0.02976582
Iteration 297, loss = 0.03077162
Iteration 298, loss = 0.03115093
Iteration 299, loss = 0.02998220
Iteration 300, loss = 0.02942386

  model  accuracy  precision  recall     f1
0   MLP    0.0875     0.0961  0.0875  0.089

## 9. Save results file

In [14]:
results.to_csv('RESULTS/models_results_ctgan.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.0733     0.0476  0.0733  0.0519
1   KNN    0.1300     0.1270  0.1300  0.1212
2    DT    0.0449     0.0708  0.0449  0.0486
3   SVM    0.1560     0.1303  0.1560  0.1330
4   MLP    0.0875     0.0961  0.0875  0.0890